### ISSUE TITLE
Crash when generating types for scoped package

### ISSUE THREAD

**Issue by ajafff** [microsoft/dts-gen#114]
```
> npx dts-gen --dt --name @iarna/toml --template module
npx: installed 59 in 5.764s
Unexpected crash! Please log a bug with the commandline you specified.
ENOENT: no such file or directory, mkdir 'types/@iarna/toml'
```

It should generate `types/iarna__toml` instead.

**Comment by hcavalieri** [comment]
@ajafff I've managed to go over this bug by creating a folder for the scope before running `dts-gen`... In your case, try creating a `@iarna` folder and then running it, it should work :)

**Comment by EthanSK** [comment]
still having this issue

**Comment by burtek** [comment]
+1
Solutin posted by @hcavalieri does not work for me - I get error when the script is unable to create `types/@scope/package/@scope/package-tests.ts`

**Comment by burtek** [comment]
@ajafff @hcavalieri @EthanSK works like a charm with `dts-gen@0.6.0` thanks to @sandersn 

This can be closed now :)
