### ISSUE TITLE
Support lookup in local node_modules

### ISSUE THREAD

**Issue by DanielRosenwasser** [Microsoft/dts-gen#14]
I think that forcing users to do a second install is a real pain since it's already installed. Is there any way we can make this work for a local `node_modules` folder?

**Comment by gozup** [comment]
+1

**Comment by RyanCavanaugh** [comment]
#16 looks to have addressed this

**Comment by DanielRosenwasser** [comment]
@RyanCavanaugh has a new version been published since #16?

**Comment by dessalines** [comment]
I can't figure out how to use this. How do I get dts-gen to scan a local module in node_modules?
