### ISSUE TITLE
Usage with private npm registry

### ISSUE THREAD

**Issue by michellocana** [microsoft/dts-gen#162]
We have a private npm registry in our company, and i tried to generate types of some of our packages, but it seems that the registry url is hard-coded [here](https://github.com/microsoft/dts-gen/blob/master/lib/definitely-typed.ts#L51) to always search in the npm registry. I think it would be a cool feature to pass an argument like `--registry` to tell the lib where to search. 

Let me know if that make sense, and if it's as simple as it seems to implement, i can help with that :)

**Comment by michellocana** [comment]
Well, i think i was using the cli wrong 😅, i figured out how to solve this problem

**Comment by harrisjose** [comment]
I think I'm doing the same thing so mind telling what was wrong?  @michellocana

**Comment by michellocana** [comment]
@harrisjose installing the package globally worked out for me, even with private registry packages
