### ISSUE TITLE
dts-gen is not able to find globally installed modules

### ISSUE THREAD

**Issue by vivekmore** [Microsoft/dts-gen#86]
I have installed dts-gen globally
`npm i -g dts-gen`

I installed the target module globally
`npm i -g jhipster-core`

When I run
`dts-gen -m jhipster-core -o`

I get the following output:
```bash
Couldn't load module "jhipster-core". Please install it globally (npm install -g jhipster-core) and try again.
```

-----
I am working on a Windows 10 PC and executing the commands on the windows command prompt.

**Comment by matez** [comment]
I experienced the same issue. It looks like error message itself is misleading in situation when module has "peer dependencies" which are not installed.

**Comment by vivekmore** [comment]
I got it working by [solution provided on stackoverflow](https://stackoverflow.com/questions/46636318/dts-gen-fails-to-find-globally-installed-modules/46640889#46640889).

**Comment by slavafomin** [comment]
Hello! I'm experiencing the same issue with `@babel/preset-env`.

Why is this issue closed without a fix? @RyanCavanaugh could you reopen it, please?
